name:PR1

on:[push]

jobs:[tell]{hello}
  build:{world}

    runs-on:ubuntu-latest
on:[push]
    steps:[jobs]+[build]
    - uses:actions/checkout@v1
    - name:Run a one-line script
      run:echo Hello, world!
    - name:Run a multi-line script
      run:[jobs]+[builds]
        echo Add other actions to build,
        echo test, and deploy your project.
env:[city]
